// <auto-generated />
using System;
using CIAbmc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIAbmc.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIAbmc.Models.Szablon", b =>
                {
                    b.Property<int>("Wersja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Wersja"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Kanaly_dotarcia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kluczowe_aktywności")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kluczowe_zasoby")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kluczowi_partnerzy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opracowane_dla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opracowane_przez")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Propozycja_wartości")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relacja_z_klientami")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segmenty_klientów")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Struktura_kosztow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strumienie_przychodów")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Wersja");

                    b.ToTable("Szablony");
                });
#pragma warning restore 612, 618
        }
    }
}
